class Translation(object):

    HELP_TEXT = """<b><u>I Know I Am A Pewer Bot 🔥</u></b>\n\n -> Any Doubt Ask : <a href=https://t.me/SBKUNJAVA>Sʙ᭄𝕂𝕌ℕ𝕁𝔸𝕍𝔸࿐</a>\n\n ✨️Help ഇല്ല അപ്പൊ എന്തായാലും വന്നത് അല്ലെ ഗ്രൂപ്പിൽ കയറിക്കോ..! <a href=https://t.me/joinchat/ZLDkX7o8pWthZTE1>Group</a>""" 
    START_TEXT = """👋Hey {},!!\nഞാൻ <a href=https://t.me/joinchat/ZLDkX7o8pWthZTE1>FILM🎬HOUSE</a> എന്ന ഗ്രൂപ്പിൽ മൂവീസ് കൊടുക്കുന്ന ബോട്ട് ആണ് \n🔊Group: <a href=https://t.me/joinchat/ZLDkX7o8pWthZTE1>FILM🎬HOUSE</a> \n🔊ᴍᴏᴠɪᴇꜱ ᴜᴘᴅᴀᴛᴇꜱ: <a href=https://t.me/kl_films>KL_FILMS</a> | <a href=https://t.me/FilmHouse_2>Film🎬House_2</a> | <a href=https://t.me/SB_Movies1>SB🎬Movies</a> \n🔊ʏᴏᴜᴛᴜʙᴇ ᴄʜᴀɴɴᴇʟ: <a href=https://youtube.com/c/THCV20>💢 ʏᴏᴜᴛᴜʙᴇ ᴄʜᴀɴɴᴇʟ 💢</a> \nMᴀɪɴᴛᴀɪɴᴇᴅ Bʏ <a href=https://t.me/SBKUNJAVA>Sʙ᭄𝕂𝕌ℕ𝕁𝔸𝕍𝔸࿐</a> | <a href=https://t.me/Film_House2>🔰ꜰɪʟᴍʜᴏᴜꜱᴇ🔰</a>"""       
    ABOUT_TEXT = """<b>➥ My Name :\n➥ Dev : <a href=https://t.me/FILMHOUSE_Kerala2>Sujin</a>\n➥ Creator : <a href=https://t.me/SBKUNJAVA>Sʙ᭄𝕂𝕌ℕ𝕁𝔸𝕍𝔸࿐</a>\n➥ Group : <a href=https://t.me/joinchat/ZLDkX7o8pWthZTE1>FILM🎬HOUSE</a>\n➥ Database : Mongo DB\n➥ Bot Server : Heroku\n➥ Language : Python 3\n➥ Source Code : <a href=https://t.me/AdhavaaBiriyaniKittiyalo>Click Me</a></b>"""
    FSUB_TEXT = """<b>Hii {}!!\nPlease Join My Updates Channel to use this Bot!</b>"""
    DYNO_TEXT = """👤Total Users {}\n🧐Total Chtas {}\n🤯Total Manul Filters {}\n🕐Bot Update Time {}"""
    INFORMATION_TEXT = """<b><u>Extra Modes</u></b>\n\n<b>NOTE:</b>\nthese are the extra features of Donlee Robot v2\n\n<b><u>Work Only Group:</u></b>:\n\n• No inline Message\n• No Forword Message\n\n<b><u>CMD Work Only Group:</u></b>\n• /report - report To admin\n\n<b><u>Commands and Usage:</u></b>\n• /id - get id about a user and group.\n• /info  - get information about a user and Group.\n• /status - Get Bot Status"""
    CREDITS_TEXT = """<u><b>DEV</b></u>\n• Muhammed RK\n\n<b><u>TroJanzHEX</u></b>\n• Unlimitedfilter\n<b><u>CrazyBotsz</u></b>\n• ADV AutoFilter V2\n<b><u>Bughunter</u></b>\n• Report\n• Ban\n<b><u>Professor-99</u></b>\n• Broadcast Bot\n• DonLee Robot 2.9 IMDB poster\n• Forword and Inline Delete\n• unban\n• [Refresh Button] Donlee Robot\n<b><u>EvamariaTG</u></b>\n• Evamaria IMDB Poster"""
    CONNECTION_TEXT = """<b><u>Connection</u></b>\n\n- Used to connect bot to PM for managing filters \n- it helps to avoid spamming in groups.\n\nNOTE:\n1. Only admins can add a connection.\n2. Send /connect for connecting me to ur PM\n\nCommands and Usage:\n• /connect  - connect a particular chat to your PM\n• /disconnect  - disconnect from a chat\n• /connections - list all your connections"""
    GROUP_ADMIN_TEXT = """<b><u>Group Commands</u></b>\n\n<b><u>Bot Master</u></b>\n• /broadcast - Replay Any Message\n\n<b><u>Group Admin Only</u></b>\n• /ban - Reply Any User Text\n• /unban - Reply Banned User Text"""
    SUB_TEXT = """JOIN, SHARE, MAXIMUM SUPPORT"""
    SPELLING_TEXT = """Hey {} Check Your Spelling"""
    STATUS_TEXT = """<b><u>Bot Status</u></b>\nTotal Users <b>{}</b>"""
